<?binding.jca CreditRatingService_db.jca?>
<wsdl:definitions name="CreditRatingService" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreditRating/CreditRating/CreditRatingService" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreditRating/CreditRating/CreditRatingService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreditRatingService">
    <plt:partnerLinkType name="CreditRatingService_plt">
        <plt:role name="CreditRatingService_role">
            <plt:portType name="tns:CreditRatingService_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreditRatingService" schemaLocation="xsd/CreditRatingService_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CreditRatingServiceSelect_inputParameters">
        <wsdl:part name="CreditRatingServiceSelect_inputParameters" element="top:CreditRatingServiceSelect_ID_NUMInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CreditRatingCollection_msg">
        <wsdl:part name="CreditRatingCollection" element="top:CreditRatingCollection"/>
    </wsdl:message>
    <wsdl:portType name="CreditRatingService_ptt">
        <wsdl:operation name="CreditRatingServiceSelect">
            <wsdl:input message="tns:CreditRatingServiceSelect_inputParameters"/>
            <wsdl:output message="tns:CreditRatingCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
