<?binding.jca customerInsert_db.jca?>
<wsdl:definitions name="customerInsert" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InitialParentInsert/InitialParentInsert/customerInsert" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InitialParentInsert/InitialParentInsert/customerInsert" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/customerInsert">
    <plt:partnerLinkType name="customerInsert_plt">
        <plt:role name="customerInsert_role">
            <plt:portType name="tns:customerInsert_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/customerInsert" schemaLocation="xsd/customerInsert_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CustomerCollection_msg">
        <wsdl:part name="CustomerCollection" element="top:CustomerCollection"/>
    </wsdl:message>
    <wsdl:portType name="customerInsert_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:CustomerCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
