<?binding.jca bankingDetailSelect_db.jca?>
<wsdl:definitions name="bankingDetailSelect" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IntialDBInsert/InitialDbInsert/bankingDetailSelect" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/bankingDetailSelect" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IntialDBInsert/InitialDbInsert/bankingDetailSelect" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="bankingDetailSelect_plt">
        <plt:role name="bankingDetailSelect_role">
            <plt:portType name="tns:bankingDetailSelect_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/bankingDetailSelect" schemaLocation="xsd/bankingDetailSelect.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="bankingDetailSelectInput_msg">
        <wsdl:part name="bankingDetailSelectInput_msg" element="db:bankingDetailSelectInput"/>
    </wsdl:message>
    <wsdl:message name="bankingDetailSelectOutput_msg">
        <wsdl:part name="bankingDetailSelectOutput" element="db:bankingDetailSelectOutput"/>
    </wsdl:message>
    <wsdl:portType name="bankingDetailSelect_ptt">
        <wsdl:operation name="bankingDetailSelect">
            <wsdl:input message="tns:bankingDetailSelectInput_msg"/>
            <wsdl:output message="tns:bankingDetailSelectOutput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
