<?binding.jca contactInfo_db.jca?>
<wsdl:definitions name="contactInfo" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IntialDBInsert/InitialDbInsert/contactInfo" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IntialDBInsert/InitialDbInsert/contactInfo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/contactInfo">
    <plt:partnerLinkType name="contactInfo_plt">
        <plt:role name="contactInfo_role">
            <plt:portType name="tns:contactInfo_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/contactInfo" schemaLocation="xsd/contactInfo_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ContactInfoCollection_msg">
        <wsdl:part name="ContactInfoCollection" element="top:ContactInfoCollection"/>
    </wsdl:message>
    <wsdl:portType name="contactInfo_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:ContactInfoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
