<?binding.jca dealDetailsSelect_db.jca?>
<wsdl:definitions name="dealDetailsSelect" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IntialDBInsert/InitialDbInsert/dealDetailsSelect" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dealDetailsSelect" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IntialDBInsert/InitialDbInsert/dealDetailsSelect" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="dealDetailsSelect_plt">
        <plt:role name="dealDetailsSelect_role">
            <plt:portType name="tns:dealDetailsSelect_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dealDetailsSelect" schemaLocation="xsd/dealDetailsSelect.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="dealDetailsSelectInput_msg">
        <wsdl:part name="dealDetailsSelectInput_msg" element="db:dealDetailsSelectInput"/>
    </wsdl:message>
    <wsdl:message name="dealDetailsSelectOutput_msg">
        <wsdl:part name="dealDetailsSelectOutput" element="db:dealDetailsSelectOutput"/>
    </wsdl:message>
    <wsdl:portType name="dealDetailsSelect_ptt">
        <wsdl:operation name="dealDetailsSelect">
            <wsdl:input message="tns:dealDetailsSelectInput_msg"/>
            <wsdl:output message="tns:dealDetailsSelectOutput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
