<?binding.jca personalInfoSelect_db.jca?>
<wsdl:definitions name="personalInfoSelect" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IntialDBInsert/InitialDbInsert/personalInfoSelect" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/personalInfoSelect" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IntialDBInsert/InitialDbInsert/personalInfoSelect" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="personalInfoSelect_plt">
        <plt:role name="personalInfoSelect_role">
            <plt:portType name="tns:personalInfoSelect_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/personalInfoSelect" schemaLocation="xsd/personalInfoSelect.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="personalInfoSelectInput_msg">
        <wsdl:part name="personalInfoSelectInput_msg" element="db:personalInfoSelectInput"/>
    </wsdl:message>
    <wsdl:message name="personalInfoSelectOutput_msg">
        <wsdl:part name="personalInfoSelectOutput" element="db:personalInfoSelectOutput"/>
    </wsdl:message>
    <wsdl:portType name="personalInfoSelect_ptt">
        <wsdl:operation name="personalInfoSelect">
            <wsdl:input message="tns:personalInfoSelectInput_msg"/>
            <wsdl:output message="tns:personalInfoSelectOutput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
