<?binding.jca customerMerge_db.jca?>
<wsdl:definitions name="customerMerge" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_App_01/Financial_Application/customerMerge" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_App_01/Financial_Application/customerMerge" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/customerMerge">
    <plt:partnerLinkType name="customerMerge_plt">
        <plt:role name="customerMerge_role">
            <plt:portType name="tns:customerMerge_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/customerMerge" schemaLocation="xsd/customerMerge_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CustomerCollection_msg">
        <wsdl:part name="CustomerCollection" element="top:CustomerCollection"/>
    </wsdl:message>
    <wsdl:portType name="customerMerge_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:CustomerCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
