--------------------------------------------------------
--  File created - Thursday-October-23-2014   
--------------------------------------------------------
CREATE USER TEST IDENTIFIED BY TEST;
GRANT DBA TO TEST;

DROP TABLE "TEST"."ACCOUNT_TYPE" cascade constraints;
DROP TABLE "TEST"."ASSET_COST" cascade constraints;
DROP TABLE "TEST"."ASSET_DETAILS" cascade constraints;
DROP TABLE "TEST"."BANKING_DETAIL" cascade constraints;
DROP TABLE "TEST"."CATEGORY" cascade constraints;
DROP TABLE "TEST"."CONTACT_INFO" cascade constraints;
DROP TABLE "TEST"."CREDIT_RATING" cascade constraints;
DROP TABLE "TEST"."CUSTOMER" cascade constraints;
DROP TABLE "TEST"."DEAL_DETAILS" cascade constraints;
DROP TABLE "TEST"."DOCUMENTS_SUBMITTED" cascade constraints;
DROP TABLE "TEST"."FINANCIAL_APPLICATION" cascade constraints;
DROP TABLE "TEST"."MYTABLE" cascade constraints;
DROP TABLE "TEST"."PAYMENT_METHOD" cascade constraints;
DROP TABLE "TEST"."PAYMENT_TYPE" cascade constraints;
DROP TABLE "TEST"."PERSONAL_INFO" cascade constraints;
DROP TABLE "TEST"."USERS" cascade constraints;
DROP SYNONYM "PUBLIC"."DUAL";
DROP SEQUENCE "TEST"."S_ASSET_COST";
DROP SEQUENCE "TEST"."S_ASSET_DETAILS";
DROP SEQUENCE "TEST"."S_BANKING_DETAIL";
DROP SEQUENCE "TEST"."S_CATEGORY";
DROP SEQUENCE "TEST"."S_CONTACT_INFO";
DROP SEQUENCE "TEST"."S_CUSTOMER";
DROP SEQUENCE "TEST"."S_DEAL_DETAILS";
DROP SEQUENCE "TEST"."S_DOCUMENTS_SUBMITTED";
DROP SEQUENCE "TEST"."S_FINANCIAL_APPLICATION";
DROP SEQUENCE "TEST"."S_MYTABLE";
DROP SEQUENCE "TEST"."S_PAYMENT_METHOD";
DROP SEQUENCE "TEST"."S_PAYMENT_TYPE";
DROP SEQUENCE "TEST"."S_PERSONAL_INFO";
DROP SEQUENCE "TEST"."S_USERS";
--------------------------------------------------------
--  DDL for Sequence S_ASSET_COST
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_ASSET_COST"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 32 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_ASSET_DETAILS
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_ASSET_DETAILS"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 32 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_BANKING_DETAIL
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_BANKING_DETAIL"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 32 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_CATEGORY
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_CATEGORY"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_CONTACT_INFO
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_CONTACT_INFO"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 32 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_CUSTOMER
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_CUSTOMER"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_DEAL_DETAILS
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_DEAL_DETAILS"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 32 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_DOCUMENTS_SUBMITTED
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_DOCUMENTS_SUBMITTED"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_FINANCIAL_APPLICATION
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_FINANCIAL_APPLICATION"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_MYTABLE
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_MYTABLE"  MINVALUE 1 MAXVALUE 11 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_PAYMENT_METHOD
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_PAYMENT_METHOD"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_PAYMENT_TYPE
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_PAYMENT_TYPE"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_PERSONAL_INFO
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_PERSONAL_INFO"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 32 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_USERS
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_USERS"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 12 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNT_TYPE
--------------------------------------------------------

  CREATE TABLE "TEST"."ACCOUNT_TYPE" 
   (	"ACCOUNT_TYPE_ID" NUMBER, 
	"ACCOUNT_TYPE_DESC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASSET_COST
--------------------------------------------------------

  CREATE TABLE "TEST"."ASSET_COST" 
   (	"ASSET_COST_ID" NUMBER, 
	"PURCHASE_PRICE" NUMBER, 
	"EXTRAS_TOTAL" NUMBER, 
	"DEPOSIT" NUMBER, 
	"TERMS" NUMBER, 
	"BALLOON_PERCENTAGE" NUMBER, 
	"ADMIN_FEES" NUMBER, 
	"DEALER_AMT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASSET_DETAILS
--------------------------------------------------------

  CREATE TABLE "TEST"."ASSET_DETAILS" 
   (	"ASSET_DETAILS_ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"IS_NEW_CAR" NUMBER(*,0), 
	"MAKE_DESC" VARCHAR2(20 BYTE), 
	"MODEL_NAME" VARCHAR2(20 BYTE), 
	"KM_TRAVELLED" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANKING_DETAIL
--------------------------------------------------------

  CREATE TABLE "TEST"."BANKING_DETAIL" 
   (	"BANKING_DETAIL_ID" NUMBER, 
	"BANK_NAME" VARCHAR2(20 BYTE), 
	"ACCOUNT_HOLDER_NAME" VARCHAR2(20 BYTE), 
	"ACCOUNT_NUMBER" NUMBER, 
	"ACCOUNT_TYPE_ID" NUMBER, 
	"BRANCH_CODE" VARCHAR2(20 BYTE), 
	"DATE_CHANGED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "TEST"."CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_DESC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTACT_INFO
--------------------------------------------------------

  CREATE TABLE "TEST"."CONTACT_INFO" 
   (	"CONTACT_ID" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"CELL_NUM" NUMBER, 
	"ADDRESS_LINE_1" VARCHAR2(20 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(20 BYTE), 
	"ADDRESS_LINE_3" VARCHAR2(20 BYTE), 
	"ADDRESS_LINE_4" VARCHAR2(20 BYTE), 
	"AREA_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CREDIT_RATING
--------------------------------------------------------

  CREATE TABLE "TEST"."CREDIT_RATING" 
   (	"ID_NUM" VARCHAR2(20 BYTE), 
	"CREDIT_RATING" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "TEST"."CUSTOMER" 
   (	"CUST_ID" NUMBER, 
	"PERSON_ID" NUMBER, 
	"CONTACT_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"BANKING_DETAIL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEAL_DETAILS
--------------------------------------------------------

  CREATE TABLE "TEST"."DEAL_DETAILS" 
   (	"DEAL_DETAILS_ID" NUMBER, 
	"PAYMENT_TYPE_ID" NUMBER, 
	"PAYMENT_FREQ" VARCHAR2(20 BYTE), 
	"PAYMENT_METHOD_ID" NUMBER, 
	"IS_FIXED_INTEREST_RATE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCUMENTS_SUBMITTED
--------------------------------------------------------

  CREATE TABLE "TEST"."DOCUMENTS_SUBMITTED" 
   (	"DOCUMENTS_SUBMITTED_ID" NUMBER, 
	"IDENTITY_DOCUMENT" VARCHAR2(20 BYTE), 
	"DRIVING_LICENSE" VARCHAR2(20 BYTE), 
	"BANK_STATEMENTS" VARCHAR2(20 BYTE), 
	"PROOF_OF_ADDRESS" VARCHAR2(20 BYTE), 
	"INSURANCE_PARTY_LETTER" VARCHAR2(20 BYTE), 
	"DEALERSHIP_QUOTE" VARCHAR2(20 BYTE), 
	"EMPLOYER_PAYSLIP" VARCHAR2(20 BYTE), 
	"DATE_SUBMITTED" DATE, 
	"DATE_MODIFIED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCIAL_APPLICATION
--------------------------------------------------------

  CREATE TABLE "TEST"."FINANCIAL_APPLICATION" 
   (	"FINANCIAL_APPLICATION_ID" NUMBER(20,0), 
	"DATE_CREATED" DATE, 
	"CUST_ID" NUMBER, 
	"ASSET_COST_ID" NUMBER, 
	"ASSET_DETAILS_ID" NUMBER, 
	"DEAL_DETAILS_ID" NUMBER, 
	"IS_QUALIFIED" VARCHAR2(20 BYTE), 
	"IS_APPROVED" VARCHAR2(20 BYTE), 
	"DOCUMENTS_SUBMITTED_ID" NUMBER, 
	"IS_DECLINED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MYTABLE
--------------------------------------------------------

  CREATE TABLE "TEST"."MYTABLE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENT_METHOD
--------------------------------------------------------

  CREATE TABLE "TEST"."PAYMENT_METHOD" 
   (	"PAYMENT_METHOD_ID" NUMBER, 
	"PAYMENT_METHOD_DESC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "TEST"."PAYMENT_TYPE" 
   (	"PAYMENT_TYPE_ID" NUMBER, 
	"PAYMENT_TYPE_DESC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONAL_INFO
--------------------------------------------------------

  CREATE TABLE "TEST"."PERSONAL_INFO" 
   (	"PERSON_ID" NUMBER, 
	"FIRST_NAMES" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"ID_NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "TEST"."USERS" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"USER_PASS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TEST.ACCOUNT_TYPE
SET DEFINE OFF;
Insert into TEST.ACCOUNT_TYPE (ACCOUNT_TYPE_ID,ACCOUNT_TYPE_DESC) values (1,'1');
REM INSERTING into TEST.ASSET_COST
SET DEFINE OFF;
Insert into TEST.ASSET_COST (ASSET_COST_ID,PURCHASE_PRICE,EXTRAS_TOTAL,DEPOSIT,TERMS,BALLOON_PERCENTAGE,ADMIN_FEES,DEALER_AMT) values (18,1,1,1,1,1,1,1);
REM INSERTING into TEST.ASSET_DETAILS
SET DEFINE OFF;
Insert into TEST.ASSET_DETAILS (ASSET_DETAILS_ID,CATEGORY_ID,IS_NEW_CAR,MAKE_DESC,MODEL_NAME,KM_TRAVELLED) values (18,1,1,'1','11',1);
REM INSERTING into TEST.BANKING_DETAIL
SET DEFINE OFF;
Insert into TEST.BANKING_DETAIL (BANKING_DETAIL_ID,BANK_NAME,ACCOUNT_HOLDER_NAME,ACCOUNT_NUMBER,ACCOUNT_TYPE_ID,BRANCH_CODE,DATE_CHANGED) values (123,'s','s',0,null,'0',to_date('12/JAN/13','DD/MON/RR'));
Insert into TEST.BANKING_DETAIL (BANKING_DETAIL_ID,BANK_NAME,ACCOUNT_HOLDER_NAME,ACCOUNT_NUMBER,ACCOUNT_TYPE_ID,BRANCH_CODE,DATE_CHANGED) values (14,'1','1',1,1,'1',to_date('12/DEC/12','DD/MON/RR'));
REM INSERTING into TEST.CATEGORY
SET DEFINE OFF;
Insert into TEST.CATEGORY (CATEGORY_ID,CATEGORY_DESC) values (1,'1');
REM INSERTING into TEST.CONTACT_INFO
SET DEFINE OFF;
Insert into TEST.CONTACT_INFO (CONTACT_ID,EMAIL,CELL_NUM,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,AREA_CODE) values (12,'11',1,'1','1','1','1','1');
REM INSERTING into TEST.CREDIT_RATING
SET DEFINE OFF;
Insert into TEST.CREDIT_RATING (ID_NUM,CREDIT_RATING) values ('test',123);
Insert into TEST.CREDIT_RATING (ID_NUM,CREDIT_RATING) values ('abc',123);
REM INSERTING into TEST.CUSTOMER
SET DEFINE OFF;
REM INSERTING into TEST.DEAL_DETAILS
SET DEFINE OFF;
Insert into TEST.DEAL_DETAILS (DEAL_DETAILS_ID,PAYMENT_TYPE_ID,PAYMENT_FREQ,PAYMENT_METHOD_ID,IS_FIXED_INTEREST_RATE) values (15,1,'1',1,1);
REM INSERTING into TEST.DOCUMENTS_SUBMITTED
SET DEFINE OFF;
REM INSERTING into TEST.FINANCIAL_APPLICATION
SET DEFINE OFF;
REM INSERTING into TEST.MYTABLE
SET DEFINE OFF;
Insert into TEST.MYTABLE (ID,NAME) values (1,'jfj');
Insert into TEST.MYTABLE (ID,NAME) values (2,'44');
Insert into TEST.MYTABLE (ID,NAME) values (3,'sdfglk');
REM INSERTING into TEST.PAYMENT_METHOD
SET DEFINE OFF;
Insert into TEST.PAYMENT_METHOD (PAYMENT_METHOD_ID,PAYMENT_METHOD_DESC) values (1,'1');
REM INSERTING into TEST.PAYMENT_TYPE
SET DEFINE OFF;
Insert into TEST.PAYMENT_TYPE (PAYMENT_TYPE_ID,PAYMENT_TYPE_DESC) values (1,'1');
REM INSERTING into TEST.PERSONAL_INFO
SET DEFINE OFF;
Insert into TEST.PERSONAL_INFO (PERSON_ID,FIRST_NAMES,LAST_NAME,GENDER,DOB,ID_NUM) values (12,'1','1','1',to_date('12/DEC/12','DD/MON/RR'),'1');
REM INSERTING into TEST.USERS
SET DEFINE OFF;
Insert into TEST.USERS (USER_ID,USERNAME,USER_PASS) values (1,'1','1');
--------------------------------------------------------
--  DDL for Index ACCOUNT_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."ACCOUNT_TYPE_PK" ON "TEST"."ACCOUNT_TYPE" ("ACCOUNT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASSET_COST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."ASSET_COST_PK" ON "TEST"."ASSET_COST" ("ASSET_COST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASSET_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."ASSET_DETAILS_PK" ON "TEST"."ASSET_DETAILS" ("ASSET_DETAILS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BANKING_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."BANKING_DETAIL_PK" ON "TEST"."BANKING_DETAIL" ("BANKING_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."CATEGORY_PK" ON "TEST"."CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTACT_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."CONTACT_INFO_PK" ON "TEST"."CONTACT_INFO" ("CONTACT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CREDIT_RATING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."CREDIT_RATING_PK" ON "TEST"."CREDIT_RATING" ("ID_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."CUSTOMER_PK" ON "TEST"."CUSTOMER" ("CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEAL_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."DEAL_DETAILS_PK" ON "TEST"."DEAL_DETAILS" ("DEAL_DETAILS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DOCUMENTS_SUBMITTED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."DOCUMENTS_SUBMITTED_PK" ON "TEST"."DOCUMENTS_SUBMITTED" ("DOCUMENTS_SUBMITTED_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FINANCIAL_APPLICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."FINANCIAL_APPLICATION_PK" ON "TEST"."FINANCIAL_APPLICATION" ("FINANCIAL_APPLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MYTABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."MYTABLE_PK" ON "TEST"."MYTABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_METHOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PAYMENT_METHOD_PK" ON "TEST"."PAYMENT_METHOD" ("PAYMENT_METHOD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PAYMENT_TYPE_PK" ON "TEST"."PAYMENT_TYPE" ("PAYMENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONAL_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."PERSONAL_INFO_PK" ON "TEST"."PERSONAL_INFO" ("PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."USERS_PK" ON "TEST"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT_TYPE
--------------------------------------------------------

  ALTER TABLE "TEST"."ACCOUNT_TYPE" MODIFY ("ACCOUNT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ACCOUNT_TYPE" MODIFY ("ACCOUNT_TYPE_DESC" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ACCOUNT_TYPE" ADD CONSTRAINT "ACCOUNT_TYPE_PK" PRIMARY KEY ("ACCOUNT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSET_COST
--------------------------------------------------------

  ALTER TABLE "TEST"."ASSET_COST" MODIFY ("ASSET_COST_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_COST" MODIFY ("PURCHASE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_COST" MODIFY ("EXTRAS_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_COST" MODIFY ("DEPOSIT" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_COST" MODIFY ("TERMS" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_COST" ADD CONSTRAINT "ASSET_COST_PK" PRIMARY KEY ("ASSET_COST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSET_DETAILS
--------------------------------------------------------

  ALTER TABLE "TEST"."ASSET_DETAILS" MODIFY ("ASSET_DETAILS_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_DETAILS" MODIFY ("IS_NEW_CAR" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_DETAILS" MODIFY ("MAKE_DESC" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_DETAILS" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_DETAILS" MODIFY ("KM_TRAVELLED" NOT NULL ENABLE);
  ALTER TABLE "TEST"."ASSET_DETAILS" ADD CONSTRAINT "ASSET_DETAILS_PK" PRIMARY KEY ("ASSET_DETAILS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANKING_DETAIL
--------------------------------------------------------

  ALTER TABLE "TEST"."BANKING_DETAIL" MODIFY ("BANKING_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."BANKING_DETAIL" MODIFY ("BANK_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEST"."BANKING_DETAIL" MODIFY ("ACCOUNT_HOLDER_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEST"."BANKING_DETAIL" MODIFY ("ACCOUNT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "TEST"."BANKING_DETAIL" MODIFY ("BRANCH_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."BANKING_DETAIL" MODIFY ("DATE_CHANGED" NOT NULL ENABLE);
  ALTER TABLE "TEST"."BANKING_DETAIL" ADD CONSTRAINT "BANKING_DETAIL_PK" PRIMARY KEY ("BANKING_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "TEST"."CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CATEGORY" MODIFY ("CATEGORY_DESC" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACT_INFO
--------------------------------------------------------

  ALTER TABLE "TEST"."CONTACT_INFO" MODIFY ("CONTACT_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CONTACT_INFO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CONTACT_INFO" MODIFY ("ADDRESS_LINE_1" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CONTACT_INFO" MODIFY ("ADDRESS_LINE_2" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CONTACT_INFO" MODIFY ("AREA_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CONTACT_INFO" ADD CONSTRAINT "CONTACT_INFO_PK" PRIMARY KEY ("CONTACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CREDIT_RATING
--------------------------------------------------------

  ALTER TABLE "TEST"."CREDIT_RATING" ADD CONSTRAINT "CREDIT_RATING_PK" PRIMARY KEY ("ID_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."CREDIT_RATING" MODIFY ("CREDIT_RATING" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CREDIT_RATING" MODIFY ("ID_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "TEST"."CUSTOMER" MODIFY ("CUST_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CUSTOMER" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CUSTOMER" MODIFY ("CONTACT_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CUSTOMER" MODIFY ("BANKING_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEAL_DETAILS
--------------------------------------------------------

  ALTER TABLE "TEST"."DEAL_DETAILS" MODIFY ("DEAL_DETAILS_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DEAL_DETAILS" MODIFY ("PAYMENT_FREQ" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DEAL_DETAILS" MODIFY ("IS_FIXED_INTEREST_RATE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DEAL_DETAILS" ADD CONSTRAINT "DEAL_DETAILS_PK" PRIMARY KEY ("DEAL_DETAILS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENTS_SUBMITTED
--------------------------------------------------------

  ALTER TABLE "TEST"."DOCUMENTS_SUBMITTED" MODIFY ("DOCUMENTS_SUBMITTED_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DOCUMENTS_SUBMITTED" MODIFY ("IDENTITY_DOCUMENT" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DOCUMENTS_SUBMITTED" MODIFY ("DRIVING_LICENSE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DOCUMENTS_SUBMITTED" MODIFY ("BANK_STATEMENTS" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DOCUMENTS_SUBMITTED" MODIFY ("PROOF_OF_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DOCUMENTS_SUBMITTED" MODIFY ("DEALERSHIP_QUOTE" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DOCUMENTS_SUBMITTED" MODIFY ("DATE_MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "TEST"."DOCUMENTS_SUBMITTED" ADD CONSTRAINT "DOCUMENTS_SUBMITTED_PK" PRIMARY KEY ("DOCUMENTS_SUBMITTED_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINANCIAL_APPLICATION
--------------------------------------------------------

  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" MODIFY ("FINANCIAL_APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" MODIFY ("CUST_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" MODIFY ("ASSET_COST_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" MODIFY ("ASSET_DETAILS_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" MODIFY ("DEAL_DETAILS_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" MODIFY ("IS_QUALIFIED" NOT NULL ENABLE);
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" MODIFY ("IS_APPROVED" NOT NULL ENABLE);
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" ADD CONSTRAINT "FINANCIAL_APPLICATION_PK" PRIMARY KEY ("FINANCIAL_APPLICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MYTABLE
--------------------------------------------------------

  ALTER TABLE "TEST"."MYTABLE" ADD CONSTRAINT "MYTABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."MYTABLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT_METHOD
--------------------------------------------------------

  ALTER TABLE "TEST"."PAYMENT_METHOD" MODIFY ("PAYMENT_METHOD_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PAYMENT_METHOD" MODIFY ("PAYMENT_METHOD_DESC" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PAYMENT_METHOD" ADD CONSTRAINT "PAYMENT_METHOD_PK" PRIMARY KEY ("PAYMENT_METHOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "TEST"."PAYMENT_TYPE" ADD CONSTRAINT "PAYMENT_TYPE_PK" PRIMARY KEY ("PAYMENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."PAYMENT_TYPE" MODIFY ("PAYMENT_TYPE_DESC" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PAYMENT_TYPE" MODIFY ("PAYMENT_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONAL_INFO
--------------------------------------------------------

  ALTER TABLE "TEST"."PERSONAL_INFO" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PERSONAL_INFO" MODIFY ("FIRST_NAMES" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PERSONAL_INFO" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PERSONAL_INFO" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PERSONAL_INFO" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PERSONAL_INFO" MODIFY ("ID_NUM" NOT NULL ENABLE);
  ALTER TABLE "TEST"."PERSONAL_INFO" ADD CONSTRAINT "PERSONAL_INFO_PK" PRIMARY KEY ("PERSON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TEST"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEST"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "TEST"."USERS" MODIFY ("USER_PASS" NOT NULL ENABLE);
  ALTER TABLE "TEST"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSET_DETAILS
--------------------------------------------------------

  ALTER TABLE "TEST"."ASSET_DETAILS" ADD CONSTRAINT "CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "TEST"."CATEGORY" ("CATEGORY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANKING_DETAIL
--------------------------------------------------------

  ALTER TABLE "TEST"."BANKING_DETAIL" ADD CONSTRAINT "ACCOUNT_TYPE_ID" FOREIGN KEY ("ACCOUNT_TYPE_ID")
	  REFERENCES "TEST"."ACCOUNT_TYPE" ("ACCOUNT_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "TEST"."CUSTOMER" ADD CONSTRAINT "BANKING_DETAIL_ID" FOREIGN KEY ("BANKING_DETAIL_ID")
	  REFERENCES "TEST"."BANKING_DETAIL" ("BANKING_DETAIL_ID") ENABLE;
  ALTER TABLE "TEST"."CUSTOMER" ADD CONSTRAINT "CONTACT_ID" FOREIGN KEY ("CONTACT_ID")
	  REFERENCES "TEST"."CONTACT_INFO" ("CONTACT_ID") ENABLE;
  ALTER TABLE "TEST"."CUSTOMER" ADD CONSTRAINT "PERSON_ID" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "TEST"."PERSONAL_INFO" ("PERSON_ID") ENABLE;
  ALTER TABLE "TEST"."CUSTOMER" ADD CONSTRAINT "USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "TEST"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEAL_DETAILS
--------------------------------------------------------

  ALTER TABLE "TEST"."DEAL_DETAILS" ADD CONSTRAINT "PAYMENT_METHOD_ID" FOREIGN KEY ("PAYMENT_METHOD_ID")
	  REFERENCES "TEST"."PAYMENT_METHOD" ("PAYMENT_METHOD_ID") ENABLE;
  ALTER TABLE "TEST"."DEAL_DETAILS" ADD CONSTRAINT "PAYMENT_TYPE_ID" FOREIGN KEY ("PAYMENT_TYPE_ID")
	  REFERENCES "TEST"."PAYMENT_TYPE" ("PAYMENT_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCIAL_APPLICATION
--------------------------------------------------------

  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" ADD CONSTRAINT "ASSET_COST_ID" FOREIGN KEY ("ASSET_COST_ID")
	  REFERENCES "TEST"."ASSET_COST" ("ASSET_COST_ID") ENABLE;
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" ADD CONSTRAINT "ASSET_DETAILS_ID" FOREIGN KEY ("ASSET_DETAILS_ID")
	  REFERENCES "TEST"."ASSET_DETAILS" ("ASSET_DETAILS_ID") ENABLE;
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" ADD CONSTRAINT "CUST_ID" FOREIGN KEY ("CUST_ID")
	  REFERENCES "TEST"."CUSTOMER" ("CUST_ID") ENABLE;
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" ADD CONSTRAINT "DEAL_DETAILS_ID" FOREIGN KEY ("DEAL_DETAILS_ID")
	  REFERENCES "TEST"."DEAL_DETAILS" ("DEAL_DETAILS_ID") ENABLE;
  ALTER TABLE "TEST"."FINANCIAL_APPLICATION" ADD CONSTRAINT "DOCUMENTS_SUBMITTED_ID" FOREIGN KEY ("DOCUMENTS_SUBMITTED_ID")
	  REFERENCES "TEST"."DOCUMENTS_SUBMITTED" ("DOCUMENTS_SUBMITTED_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ASSET_COST_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_ASSET_COST_ID" 
BEFORE INSERT
ON ASSET_COST
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.ASSET_COST_ID is null) then
  SELECT S_ASSET_COST.nextval
  INTO :new.ASSET_COST_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_ASSET_COST_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ASSET_DETAILS_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_ASSET_DETAILS_ID" 
BEFORE INSERT
ON ASSET_DETAILS
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.ASSET_DETAILS_ID is null) then
  SELECT S_ASSET_DETAILS.nextval
  INTO :new.ASSET_DETAILS_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_ASSET_DETAILS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_BANKING_DETAIL_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_BANKING_DETAIL_ID" 
BEFORE INSERT
ON BANKING_DETAIL
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.BANKING_DETAIL_ID is null) then
  SELECT S_BANKING_DETAIL.nextval
  INTO :new.BANKING_DETAIL_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_BANKING_DETAIL_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CATEGORY_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_CATEGORY_ID" 
BEFORE INSERT
ON CATEGORY
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.CATEGORY_ID is null) then
  SELECT S_CATEGORY.nextval
  INTO :new.CATEGORY_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_CATEGORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CONTACT_INFO_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_CONTACT_INFO_ID" 
BEFORE INSERT
ON CONTACT_INFO
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.CONTACT_ID is null) then
  SELECT S_CONTACT_INFO.nextval
  INTO :new.CONTACT_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_CONTACT_INFO_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CUSTOMER_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_CUSTOMER_ID" 
BEFORE INSERT
ON CUSTOMER
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.CUST_ID is null) then
  SELECT S_CUSTOMER.nextval
  INTO :new.CUST_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_CUSTOMER_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_DEAL_DETAILS_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_DEAL_DETAILS_ID" 
BEFORE INSERT
ON DEAL_DETAILS
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.DEAL_DETAILS_ID is null) then
  SELECT S_DEAL_DETAILS.nextval
  INTO :new.DEAL_DETAILS_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_DEAL_DETAILS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_DOCUMENTS_SUBMITTED_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_DOCUMENTS_SUBMITTED_ID" 
BEFORE INSERT
ON DOCUMENTS_SUBMITTED
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.DOCUMENTS_SUBMITTED_ID is null) then
  SELECT S_DOCUMENTS_SUBMITTED.nextval
  INTO :new.DOCUMENTS_SUBMITTED_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_DOCUMENTS_SUBMITTED_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_FINANCIAL_APPLICATION_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_FINANCIAL_APPLICATION_ID" 
BEFORE INSERT
ON FINANCIAL_APPLICATION
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.FINANCIAL_APPLICATION_ID is null) then
  SELECT S_FINANCIAL_APPLICATION.nextval
  INTO :new.FINANCIAL_APPLICATION_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_FINANCIAL_APPLICATION_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_MYTABLE_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_MYTABLE_ID" 
BEFORE INSERT
ON MYTABLE
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.ID is null) then
  SELECT S_MYTABLE.nextval
  INTO :new.ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_MYTABLE_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_PERSON_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_PERSON_ID" 
BEFORE INSERT
ON PERSONAL_INFO
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.PERSON_ID is null) then
  SELECT S_PERSONAL_INFO.nextval
  INTO :new.PERSON_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_PERSON_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_USERS_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."T_USERS_ID" 
BEFORE INSERT
ON USERS
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  if(:new.USER_ID is null) then
  SELECT S_USERS.nextval
  INTO :new.USER_ID
  FROM dual;
  end if;
END;
/
ALTER TRIGGER "TEST"."T_USERS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
