<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="AffordabilityDecisionService_2"
     targetNamespace="http://xmlns.oracle.com/AffordabilityRule2/AffordabilityDecisionService_2"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/AffordabilityRule2/AffordabilityDecisionService_2"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="AffordabilityRule2.AffordabilityDecisionService_2">
        <plnk:role name="IDecisionService" portType="tns:IDecisionService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/AffordabilityRule2/AffordabilityDecisionService_2"
         location="AffordabilityDecisionService_2.wsdl"/>
</wsdl:definitions>
