<?binding.jca creditRatingUpdate_db.jca?>
<wsdl:definitions name="creditRatingUpdate" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_App_01/CreditRating/creditRatingUpdate" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_App_01/CreditRating/creditRatingUpdate" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/creditRatingUpdate">
    <plt:partnerLinkType name="creditRatingUpdate_plt">
        <plt:role name="creditRatingUpdate_role">
            <plt:portType name="tns:creditRatingUpdate_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/creditRatingUpdate" schemaLocation="xsd/creditRatingUpdate_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CreditRatingCollection_msg">
        <wsdl:part name="CreditRatingCollection" element="top:CreditRatingCollection"/>
    </wsdl:message>
    <wsdl:portType name="creditRatingUpdate_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:CreditRatingCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
